export type Quest = {
  id?: string;
  collectionId: string;
  collectionName: string;
  name?: string;
  lat?: number;
  lng?: number;
  type?: "box" | "detect" | "collect" | "none";
  description?: string;
  radius?: number;
  generic?: boolean;
  detect?: string[];
  help?: string;
  detect_label?: string;
  image?: string;
  required?: string[];
  expand: any;
  outdoor?: boolean;
  sphere?: string;
  distance?: number;
  infobox?: string;
  infobox_en?: string;
  group?: string;
  group_en?: string;
  info_or?: string;
  info_or_en?: string;
  info_wr?: string;
  info_wr_en?: string;
  literature?: string;
  literature_en?: string;
};
